### ISSUE TITLE
Use communityId in the Matching, survey and Inventory data models.

### ISSUE THREAD

**Issue by logicsandeep** [hserv/coordinated-entry#10]
Use communityId in the Matching as well as Service data models.:
The matching needs to be done for (homeless) clients with in a community and not for all the client. Hence, we should include communityId into these data models. I may need community ID in the Inventory data model too.

**Comment by eric-jahn** [comment]
This may be an hmislynk issue though, since homeless client records should never "bleed" between communities, unless that type of sharing is specifically enabled (selective client info sharing is functionality we have not implemented yet).

**Comment by eric-jahn** [comment]
Can we close this, because we decided we'll determine the community ID from the given user context, since a user can belong to only one community?

**Comment by suryayadavalli** [comment]
Yes, we are fetching the data based on user's project group ID (community ID)
