### ISSUE TITLE
email transmission log to verify all is well

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#101]
Is there a way we can get a log of all recent emails sent out and if they were transmitted successfully?  Does Amazon keep such a thing for us, since we use their email? Roxanne is wondering if they are always going out, or if the users just aren't checking their spam or whitelisting.  Some users have received their emails, so I suspect it's the latter, but I just want to show them a log. @CTAJavier  included, so he is notified of the progress on this.

**Comment by eric-jahn** [comment]
also digital email signing the issue per Surya - on 12/13/16

**Comment by suryayadavalli** [comment]
Notification service was designed to log the status of each and every notification that is being sent out from the system. Verified that the micro service is implemented as per the design. 

**We can provide the following information.**
- **who** (which email Id) 
- **when** (date & time the user was notified) / 
- **why** (purpose of the notification - could be password reset or agency email) / 
- **status**  (success or failure) 

**Here is some metrics from our notification log** (there are 132 emails on 10/05 and I see that there were many user activations on that day)
	No of emails | Date
	5----------2016-10-20
	2----------2016-11-02
	1----------2016-12-16
	8----------2016-10-09
	8----------2016-10-31
	3----------2016-12-01
	1----------2016-12-15
	2----------2016-11-03
	2----------2016-10-18
	2----------2016-11-05
	5----------2016-12-13
	5----------2016-12-09
	3----------2016-09-15
	3----------2016-12-06
	10----------2016-10-12
	1----------2016-11-22
	2----------2016-09-13
	3----------2016-10-27
	8----------2016-10-06
	2----------2016-09-23
	1----------2016-12-05
	2----------2016-09-28
	4----------2016-10-10
	3----------2016-11-28
	1----------2016-11-08
	3----------2016-11-16
	132--------2016-10-05
	17----------2016-10-19
	1----------2016-09-17
	2----------2016-11-14
	1----------2016-09-14
	2----------2016-11-18
	2----------2016-12-07
	3----------2016-10-07
	1----------2016-10-11
	2----------2016-11-17
	1----------2016-11-15
	3----------2016-10-08
	1----------2016-12-02
	2----------2016-10-28
	19----------2016-09-12
	7----------2016-09-19
	1----------2016-11-09
	2----------2016-09-21
	13----------2016-10-04
	2----------2016-11-07
	17----------2016-09-16
	6----------2016-10-25
	2----------2016-11-11
	1----------2016-11-10

**Comment by eric-jahn** [comment]
can we send a customer the recipient email and transmission status for this history?
