### ISSUE TITLE
DKIM signature for emails

### ISSUE THREAD

**Issue by suryayadavalli** [hserv/coordinated-entry#103]

**Comment by eric-jahn** [comment]
On 12/13/16, the team discussed this as a means to ensure emails are delivered successfully to recipients, during the CES match process.

**Comment by eric-jahn** [comment]
I'm wondering if this is specific to CES, or whether we should move this issue to the other general tracker.  I know we only use email for CES right now, but ideally, email notification could be for other purposes.

**Comment by suryayadavalli** [comment]
Resolved, set up DKIM signature for the domain so the emails do not go to spam
![image](https://cloud.githubusercontent.com/assets/10738348/21367451/179a1748-c6b3-11e6-8558-b3a152076910.png)
