### ISSUE TITLE
notes on why match process skipped for a client

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#107]
per @CTAJavier's request today, if "ignoreMatchProcess" is set for a client, we should offer a free text notes field to explain why they were skipped.  I suppose this could also be used to put a notes as to why they should not be skipped. 
originating/related issue: https://github.com/hserv/coordinated-entry/issues/106

**Comment by suryayadavalli** [comment]
Deployed in production. 
https://github.com/hserv/coordinated-entry/commit/cd33ed71226dbba5ca532a7703f05fbbbaf4b960

The field is set to non-mandatory . This will be enabled once HOME makes necessary changes on their UI  for this field
