### ISSUE TITLE
Match process not returning any clients

### ISSUE THREAD

**Issue by suryayadavalli** [hserv/coordinated-entry#108]
@CTAJavier : we looked at the match log (for the housing match process you run) and here are the findings.

The clients are not getting matched because they are registered in **global house hold** . 

You can verify this using the following
http://52.40.10.206:8080/processlogui/processlog.html?theme=classic
enter **processId** as :  df6b8525-476c-4fc4-8709-9d516cab12e8
You can also input client Id or a housing unit id if you would like to look at the log, at that level

Here is the snapshot for the same,
![image](https://cloud.githubusercontent.com/assets/10738348/22180107/7551d4a0-e08c-11e6-8064-5d111c472ea6.png)

**Comment by logicsandeep** [comment]
Hey @suryayadavalli  We may have to search for the following project IDs:
524ac086-fc21-4f40-84ac-cf58d8f99830
a7ac82b3-d54b-4b63-8f8b-71dfa04bcbde
06cf7e73-e754-4861-9788-5f4f72c4f9e4
45e11ab7-1b96-44a2-83ec-a68632d9a6b0
c5ee556c-a5e4-4e30-8fe9-dfa7a03a024c
a1972983-c32f-4cce-9b2e-84f53e0afecd
b382948f-0174-40be-bc35-57f43f9aba34
1f151eec-afd2-4a50-83ee-deacab4ce793
45fd3501-70ec-4240-becc-d50de56fab41
b7044b6e-e68a-42e3-8ceb-116faaf8e4a9
908cf1dd-e2f6-499c-a956-09575e4dd814
2d11ca78-1679-4055-8890-d83a824bee7b
d083da8c-c3c3-449d-b361-415fe12da800
b994fef1-ed50-4aad-9c1b-49b48e86cb2d
7858afb2-d1a9-4c7b-833d-91aec90389e9

And I only see data for the below project ids in the match process logs.

524ac086-fc21-4f40-84ac-cf58d8f99830
b7044b6e-e68a-42e3-8ceb-116faaf8e4a9
908cf1dd-e2f6-499c-a956-09575e4dd814

I'm going to further investigate on why we're not seeing all the projects in the match processing log table.
![house matching](https://cloud.githubusercontent.com/assets/4108057/22180303/ee6f6952-e031-11e6-82e4-638626a90db0.png)

**Comment by suryayadavalli** [comment]
There is a successful match after making the changes to consider the house hold size 1, in case there is no global house hold data for the client. There is no project eligibility requirements for the project to which the housing unit belongs to.  

Here is the processId : 508b657c-d230-40e3-81a4-7b3fa02bb81f
Please go to the following page and enter the process Id, to get details
http://52.40.10.206:8080/processlogui/processlog.html?theme=classic

**Comment by suryayadavalli** [comment]
Completed, Deployed and verified in Production
