### ISSUE TITLE
notes in client profile

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#112]
It will be a simple notes log with user and time details.  Can inactivate (not really delete) a note that is no longer appropriate.  Not sure about editing an old note yet.  (userID, timestamp, etc.).  Also need to store stage # the note is associated with.  Should take 3-4 days effort including testing.  Please see all comments here: https://trello.com/c/WteDfozK/45-after-referral-is-accepted-how-can-a-unit-be-re-released-if-the-client-or-agency-backed-up-out-of-the-enrollment

**Comment by suryayadavalli** [comment]
We will discuss in 02/14's meeting however, here are my comments.

Currently there is a remarks field in the eligible clients sections, that can accommodate any notes. I came up with an API to be able to POST notes for an eligible client.  So, when we retrieve the eligible clients, all the notes associated with the eligible client will be given as an array  , with each element consists of the following

- Date & time
- Created By
- Notes 

Also, ability to DELETE a notes is not something that is recommended as notes is like a audit log to track, and once it's posted, it should be in there for tracking purposes. User can always add new notes .

**Comment by suryayadavalli** [comment]
@eric-jahn : This issue hasn't been worked upon yet. I will working on this , this week.

**Comment by suryayadavalli** [comment]
Commit URL:
https://github.com/hserv/coordinated-entry/commit/9ff9e719375f0261b278dd31381522cec057b0e3
