### ISSUE TITLE
Ability to delete a housing unit assignment

### ISSUE THREAD

**Issue by suryayadavalli** [hserv/coordinated-entry#113]

**Comment by eric-jahn** [comment]
See https://trello.com/c/WteDfozK/45-after-referral-is-accepted-how-can-a-unit-be-re-released-if-the-client-or-agency-backed-up-out-of-the-enrollment

> We

 would need to provide reasons why the referral is rejected manually....
1. Contact information for client is out of date. (This will remove the client from the Active List.)
2. Client Refused. (This will put the client back onto the Active List, if this is the first time a client refused. If it is the second time, the client is removed from the list.)If this option is selected, we need an explanation box.
3. Agency Refused. (This will put the client back onto the Active List.) If this option is selected, we need an explanation box.
4. Client is currently housed. (This removes them from the list.)

>
