### ISSUE TITLE
new eligibility logic needed - single mom with kids

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#115]
For eligibility screening, we need to add new logic for "single mom, with kids (three max kids), up to four people in a housing unit"

cc: @logicsandeep

**Comment by suryayadavalli** [comment]
This is complete. We are now populating the new DE for the client momWithNoOfKids 

However we need more inputs from @CTAJavier on few things
Should we consider the transgender Male to Female also for the single Mom condition ?
How do we determine the relationship of the house hold members with the client. Currently we are looking the "relationship to household" value in global house hold members entity - however, these values doesn't seem to be populated correctly. 

We see the following values for this relationship column currently.  We can restrict the values on the API so, we will be consistent in what values this API can accept , So we can always rely on this data . Please suggest

- test,
- 2,
- Head of household's spoude or partner,
- 5,
- Head of household's child,
- 3,
- 1,
- Other: non-relation member

**Comment by eric-jahn** [comment]
So scratch the use of relationships, and per @CTAJavier, within a global household, over 18 and female = we assume is the adult mom, <18 we assume are her kids

**Comment by suryayadavalli** [comment]
Working on this today and should be able to deploy tomorrow

**Comment by suryayadavalli** [comment]
Complete, Deployed in Production.
