### ISSUE TITLE
create API for manual override of each match step

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#118]
A user with privileges over the match process should be able to "force" matches, to move a client through the match process, despite the eligibility rules disagreeing with a match.  This will allow clients to use our matching system in situations where automated matching is not working according to expectations, for whatever reason.
@CTAJavier

**Comment by CTAJavier** [comment]
Closing this issue it is very similar to issues 73 and 120, We can continue to track it on Issue 73 since that is the best description will add details to that one. https://github.com/hserv/coordinated-entry/issues/73
