### ISSUE TITLE
Need to create Enum for Project Type for Matching Service

### ISSUE THREAD

**Issue by logicsandeep** [hserv/coordinated-entry#12]

**Comment by Dinesh846** [comment]
Have started the implementation, will change that to numbers rather than PSH/RRH, as that's the standard being followed elsewhere in the hserv.

**Comment by eric-jahn** [comment]
@suryayadavalli: is this still an issue?

**Comment by suryayadavalli** [comment]
This is not an issue any more. We are fetching the project type from the project type entity (so, no hardcoding of the project type is in place). Closing the issue
