### ISSUE TITLE
gui based Match workflow configuration

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#120]
request from @CTAJavier.  Using something like https://scratch.mit.edu/ or maybe BPEL/BPMN visualizations.  Then, a community could visually configure their specific matching workflows by dragging and dropping component blocks around.

**Comment by CTAJavier** [comment]
Closing this issue it is very similar to issues 73 and 120, We can continue to track it on Issue 73 since that is the best description will add details to that one. #73
