### ISSUE TITLE
Issue with active list search on HOME APP

### ISSUE THREAD

**Issue by suryayadavalli** [hserv/coordinated-entry#123]
Clients are showing up in the search on HOME APP Active list screen. However,  HOME APP on active list screen - there are few entries with Client ID and there are few entries with Client name (not sure why)  so , the internal search with in the page (on active list) doesn't work for client ids, where Names are displayed and doesn't work with names where client ids are displayed.

**Comment by eric-jahn** [comment]
This is a HOME App issue, which I added to their issue tracker.  We could also add more to our API docs clarifying this.
