### ISSUE TITLE
/eligibleclients should return client information in its response 

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#125]
from @pgorecki "need first, middle, last name and schema for each client fetched via house matching api"

**Comment by eric-jahn** [comment]
@suryayadavalli reported this should be implemented by 8/18/17. After he finishes https://github.com/servinglynk/hmis-lynk-open-source-docs/issues/302

**Comment by eric-jahn** [comment]
@suryayadavalli will be able to push this by Friday, 9/8.

**Comment by suryayadavalli** [comment]
This will be addressed for survey responses API as well. (returning the client element during the survey responses)

**Comment by eric-jahn** [comment]
@suryayadavalli still needs to share the docs with @pgorecki , since it's deployed and ready.

**Comment by suryayadavalli** [comment]
API Documentation URLs:
  Survey API : 
 
-    https://hmis-api.github.io/survey-service-api/#v2_clients__clientid__surveys__surveyid__responses_get
- https://hmis-api.github.io/survey-service-api/#v2_clients__clientid__surveys__surveyid__responses__responseid__get 

House Matching API:

- https://hmis-api.github.io/housing-matching-service-api/#v2_eligibleclients_get
- https://hmis-api.github.io/housing-matching-service-api/#v2_eligibleclients__clientid__get

**Comment by eric-jahn** [comment]
@pgorecki confirmed this is complete.  cc: @CTAJavier
