### ISSUE TITLE
graceful handling of invalid client SSNs

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#127]
involves Open EMPI dedupe ID.  It is a valid test use case for 123456789 to be transmitted in testing. cc: @CTAJavier 

possible solutions: 
-default ssn
-pre-open empi error handling
-update docs

**Comment by suryayadavalli** [comment]
Closed with @logicsandeep fix for http://github.com/servinglynk/hmis-lynk-open-source-docs/issues/336
