### ISSUE TITLE
"/eligibleclients get" should throw an error status code when there is an exception

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#129]
@pgorecki and @CTAJavier reported in https://github.com/servinglynk/hmis-lynk-open-source-docs/issues/337 , that null payloads were being returned with a status code 200.  A server error was causing it.  The 200 successful response code caused the notification system to not alert us, as a 400/500 code would have.

**Comment by eric-jahn** [comment]
@suryayadavalli will research this, and get back on this.  He needs to verify the 200 indeed happened.

**Comment by eric-jahn** [comment]
This is a generic task for CES only.  Mapping may be missing.  one-half to 1 day just for this issue per both developers.  Testing, etc. included.

**Comment by suryayadavalli** [comment]
This must be an intermittent error that occurred and should be something to do with some network data transmission. Verified all the APIs and API doesn't return a HTTP 200 , when there is an error. We will re-open this issue, if this ever happens again to analyse further.
