### ISSUE TITLE
empty links:[] in v2/eligibleclients get

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#130]
from @pgorecki : ...for another client `27eb1139-d94b-4961-9ee1-c3c4b86f9fc2` links attribute is empty.
```
I20170920-14:17:55.186(2)?       [ { clientId: '27eb1139-d94b-4961-9ee1-c3c4b86f9fc2',
I20170920-14:17:55.187(2)?           surveyScore: 5,
I20170920-14:17:55.187(2)?           programType: '2',
I20170920-14:17:55.187(2)?           matched: false,
I20170920-14:17:55.188(2)?           surveyDate: '12-09-2016 00:00',
I20170920-14:17:55.190(2)?           spdatLabel: 'SINGLE_ADULT',
I20170920-14:17:55.190(2)?           dateCreated: '01-09-2017 19:26:51.161',
I20170920-14:17:55.191(2)?           dateUpdated: '03-14-2017 16:56:24.747',
I20170920-14:17:55.191(2)?           ignoreMatchProcess: false,
I20170920-14:17:55.191(2)?           remarks: 'Ignore match flag auto set by system to false',
I20170920-14:17:55.191(2)?           client: 
I20170920-14:17:55.191(2)?            { id: '27eb1139-d94b-4961-9ee1-c3c4b86f9fc2',
I20170920-14:17:55.191(2)?              firstName: 'XXX',
I20170920-14:17:55.192(2)?              middleName: '',
I20170920-14:17:55.192(2)?              lastName: 'XXX',
I20170920-14:17:55.192(2)?              dob: XXX },
I20170920-14:17:55.192(2)?           links: [] },
```
 ... Without the `links[0].href` I'm unable to make any subsequent calls for this client (i.e. get details via client api)

**Comment by eric-jahn** [comment]
4 hours to 8 hours per @suryayadavalli

**Comment by suryayadavalli** [comment]
Analysed this issue , No coding changes required. Here is some information about the ticket.

The client in question is  27eb1139-d94b-4961-9ee1-c3c4b86f9fc2, belongs to  MO0010  (base and version). However, this was accessed by HOME APP user on 12/09/2016 fernando.c@toptal.com  (Home App)  | Survey Date | 12/9/2016 0:00 |   and this client is populated as eligible client on 01/09/2017 - This is before the Project group security restriction was added  (Restrictions are deployed on 01/18/2017).

Data issue and will not occur with the current implementation
