### ISSUE TITLE
Enable Global client ID support for CES APIs

### ISSUE THREAD

**Issue by suryayadavalli** [hserv/coordinated-entry#133]
We have HMIS version specific client IDs in The CES.  This tightly couples CES to a specific year of HMIS.

**Comment by eric-jahn** [comment]
By EOD, Surya will have questions and a preliminary plan to discuss.

**Comment by suryayadavalli** [comment]
Working on this phase wise due to the amount of the changes required and scenarios that need to be considered. 
1) Global house hold changes to honor global client id.
2) Survey API changes to honor global client id.
3) No changes required to Housing units, as its not client specific.
4) House matching API changes to consider dedup / global Id as opposed to version specific client id.

**Changes for global house hold API**
STEP 1 :  change global house hold APIs to accept dedup Id 
  1.1 :  Maintain dedup Id (also) along with client identifier
  1.2 :  Modify APIs to accept global client identifier. These APIs will be exposed as V2 APIs. 
1.2.1 Detailed changes
1) Add new column dedup_id in global_household and household_membership tables.
2) Insert client dedup id in global_household and household_membership tables in existing API.
3) Change logic to get schema year and client id while retriving data.

New APIs,
1) Implement CRUD operations for global_household and household_membership tables, DEDUP id as unique identifier.
2) Delete logic, latest schema year record will be deleted on delete request.
Ex: 
        RNO                client_id                                        dedup_id                                           schema_year    
1       12334edb-2118-4309-ab44-88a72ef2363d4     e65d6a40-675d-11e6-ab44-02f305dabccf      2014
2       24534edb-3914-675d-a942-59a743ef32424     e65d6a40-675d-11e6-ab44-02f305dabccf      2015
3       88434edb-5916-11e6-675d-e65d6a4323d4     e65d6a40-675d-11e6-ab44-02f305dabccf      2016

On first delete request, record 3 will be deleted - as we will be deleting the latest client in this case client record belongs to version 2016
On second delete request, record 2 will be deleted - as we will be be deleting the latest client and in this case client belongs to version 2015 ( client from version 2016 is already deleted)

**Comment by eric-jahn** [comment]
@suryayadavalli will be finished by Monday.  Deploying Tuesday.

**Comment by eric-jahn** [comment]
@suryayadavalli could you close this with the commit ID?

**Comment by eric-jahn** [comment]
@suryayadavalli just a reminder to close this with the commit id.

**Comment by suryayadavalli** [comment]
commit https://github.com/hserv/coordinated-entry/commit/3f463b939c96964b1586cef629592d70d8978a43
