### ISSUE TITLE
Global client Identifier changes - Survey Micro service

### ISSUE THREAD

**Issue by suryayadavalli** [hserv/coordinated-entry#135]

**Comment by suryayadavalli** [comment]
dependent on  #136 and #137

**Comment by eric-jahn** [comment]
@suryayadavalli will be finished with this by end of day today

**Comment by suryayadavalli** [comment]
Commit id #https://github.com/hserv/coordinated-entry/commit/0f4d572fb1ce2ee044bbe11089319e2c98ebe2bd

Link to documentation : https://github.com/hmis-api/survey-service-api/commit/4cfab4d90700b75d14c035cd591e95afc7161315
