### ISSUE TITLE
Global client Identifier changes - House Matching service

### ISSUE THREAD

**Issue by suryayadavalli** [hserv/coordinated-entry#138]
Will update the detailed tasks here by EOD 11/17.

**Comment by eric-jahn** [comment]
@suryayadavalli will be finished by Monday.  Deploying Tuesday.

**Comment by suryayadavalli** [comment]
Commit id https://github.com/hserv/coordinated-entry/commit/fa3dfbf8b5121f358192484736c551b73edf4e7c

Documentation commit id https://github.com/hmis-api/survey-service-api/commit/4cfab4d90700b75d14c035cd591e95afc7161315

Link to documentation : https://hmis-api.github.io/housing-matching-service-api/
