### ISSUE TITLE
Active List sync is slow

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#141]
1) Active List sync needs to complete quickly,  It appears that a large number of disabilities data uploaded via XML is taking to long to sync with new client information uploaded by HOME App.  
2) Need an alert when it fails
3) Need detailed description of what the issue was, and how it was fixed (code or data or deployment).

**Comment by eric-jahn** [comment]
@logicsandeep is setting up email  to customer admin and Prometheus alerts when sync is brought up, down or fails.

**Comment by eric-jahn** [comment]
New branch created to fix sync speed: https://github.com/servinglynk/hmis-lynk-open-source/tree/sync-improvements
cc: @CTAJavier

**Comment by eric-jahn** [comment]
https://github.com/servinglynk/hmis-lynk-open-source/commit/afa282c8d5a57084d243b22c4a49520c803c095e

**Comment by eric-jahn** [comment]
@logicsandeep is this completed?

**Comment by eric-jahn** [comment]
@logicsandeep could you update this issue or close it with the commit id?

**Comment by eric-jahn** [comment]
@logicsandeep can you close this issue if you are done with it?  I see you already have the commit id above.

**Comment by logicsandeep** [comment]
Yes, this issue can be closed.
