### ISSUE TITLE
Clients from HOME App Project group are not visible in Active List

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#146]
cc: @pgorecki @CTAJavier 
**_Client information_**
- A******-2dbd-4***-aaf9-c25ec48d02fa
- Uploaded Last week
- Visible in Client List

**Comment by suryayadavalli** [comment]
Debugged this issue further. Initially HOME APP used to populate the active list manually (by hitting a button from the Web UI). We set up automated job to populate the active list only for Monterey project group, but not Home app project group.

Set up and configuring this job for Home app project group would address this issue.  Will be complete by 12/13.

**Comment by eric-jahn** [comment]
@suryayadavalli: is this complete?

**Comment by suryayadavalli** [comment]
DB change was made as per @jceledon. Conplete and verified by CTA
