### ISSUE TITLE
HSLynk returning a 404 when submitting survey responses from Monterey project group

### ISSUE THREAD

**Issue by suryayadavalli** [hserv/coordinated-entry#147]

**Comment by eric-jahn** [comment]
Is this resolved?

**Comment by suryayadavalli** [comment]
This is resolved. The issue is specific to data migration - as the questions are associated with HOME project group, as they are created by HOME user. However, as per @CTAJavier , they would like these questions to be associated with Monterey project group. Changes are complete and verified by HOME
