### ISSUE TITLE
GET eligibleclients returns no records for MONTEREY project group.

### ISSUE THREAD

**Issue by suryayadavalli** [hserv/coordinated-entry#150]

**Comment by CTAJavier** [comment]
Can you guys please make this a priority this is blocking us from releasing V2 of HOME

**Comment by suryabi** [comment]
@CTAJavier , we will address this by EOD today.

**Comment by suryabi** [comment]
@CTAJavier: This is resolved now. Please verify.

**Comment by CTAJavier** [comment]
Verified,  thanks working as expected

**Comment by suryayadavalli** [comment]
Commit id : https://github.com/hserv/coordinated-entry/commit/27e87841d4ddf2e388f3558dab6d2ada213c8cca
