### ISSUE TITLE
v3 Survey docs in wiki

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#155]
We need documentation for the workflow when using the survey APIs, to complement the API endpoint docs.

cc: @CTAJavier @pgorecki

**Comment by suryayadavalli** [comment]
| Step   description | Notes | POST  / GET | GET / UPDATE /   DELETE (key records)
-- | -- | -- | -- | --
Step : 1 | Create   question Groups | A   question group is nothing but a category for a set up questions. You can have   100 questions however, all of these questions could be categorized into four   groups (personal, finacial, work etc.). | /questiongroups | /questiongroups/{questiongroupid}
Step : 2 | Create   questions for a question group | Once   the quesiton group is created you can add questions to the group           Each question can have a title / text / definition (JSON), pick list values   (stored as a stringfied JSON) and other elements, including visibility ,   category and sub-category | POST   /v2/questiongroups/{questiongroupid}/questions     GET /v2/questiongroups/{questiongroupid}/questions | /v2/questiongroups/{questiongroupid}/questions/{questionid}
Step : 3 | Create   a survey | A   JSON document containing the entire defintion of the survey including the   sections / quesitons etc. | POST /v2/surveys | /v2/surveys/{surveyid}
Step: 4 | Create   survey sections | Although   entire survey definition is stored as a document , survey sections need to be   created in HSLynk to be able to POST scores for the clients against these   sections | POST   /surveys/{surveyid}/surveysections | /surveys/{surveyid}/surveysections/{sectionid}
