### ISSUE TITLE
Add additional fields to support Question schema for HOME

### ISSUE THREAD

**Issue by suryayadavalli** [hserv/coordinated-entry#161]
As per the following question schema for HOME , HSLynk currently doesn't support additional description and visibility, category and subcategory elements. 

field | type | description
-- | -- | --
hmisId | string | id
title | string | Question title
text | string | additional description to display
type | string | choice\|text\|number\|date\|grid
definition | String (JSON serialized data) |  
definition.mask | string | Text input mask, i.e. for phone number
definition.category | string | One of: choice\|text\|number\|date\|grid
definition.options | Array of string | Used by choice category (aka picklist values)
definition.refusable | bool | Can client refuse to answer
definition.other | bool | Does q. have other option (Used by choice category)
definition.otherValue | string | Text under other option
visibility | bool | Show this question in the survey builder
category | string |  
subcategory | string |  
createdBy | String, hmis userId |  
createdAt | time |

**Comment by suryayadavalli** [comment]
https://github.com/hserv/coordinated-entry/commit/1cecfa2f06cb3560ba05dee7c09f5a5638c38dbe

**Comment by eric-jahn** [comment]
Can we close this?
