### ISSUE TITLE
typo in /surveys GET

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#169]
I20171227-15:53:32.970(1)? debug: HMIS API:get#6 res (https://www.hmislynk.com/survey-api/rest/v2/surveys) 200
I20171227-15:53:32.972(1)? { survies: 
I20171227-15:53:32.972(1)?    { pagination: { from: 0, returned: 30, total: 122, maximum: 30, sort: {} },
I20171227-15:53:32.972(1)?      survies: 
I20171227-15:53:32.972(1)?       [ [Object], [Object], [Object], ...

"are you sure there should be `survies` property not `surveys`? And we have it correct in the API, so this is a bug.  https://hmis-api.github.io/survey-service-api/#v2_surveys_get"
cc: @pgorecki

**Comment by suryayadavalli** [comment]
commit https://github.com/hserv/coordinated-entry/commit/65a24edf76772a90bb4a1bdde1e4c3ea1f539fa1

documentation https://hmis-api.github.io/survey-service-api/#v2_surveys
