### ISSUE TITLE
Call Notification Service

### ISSUE THREAD

**Issue by Dinesh846** [hserv/coordinated-entry#17]
As part of Monterey specific requirements, notification should be sent to admins to approve of a proposed match. Re-use hmis services.

**Comment by eric-jahn** [comment]
We need the notification service's methods to be made available to third party apps in HMISLynk's Client Core module.  https://github.com/servinglynk/hmis-lynk-open-source-docs/issues/97

**Comment by eric-jahn** [comment]
per @suryayadavalli on 10/7/16, Javier gave us a template sheet to apply.

**Comment by eric-jahn** [comment]
complete per @suryayadavalli
