### ISSUE TITLE
Remove or Replace Null dedup_client_id in Enrollment, Active_list and client table. 

### ISSUE THREAD

**Issue by sachs089** [hserv/coordinated-entry#174]
@sandeep.dolia There are multiple records in enrollment table which have Null dedup_client_id. The same problem exists with active list and client table (Although client table has a few records with such anomaly).  We can change the joins in existing data models until this gets fixed. Please do the needful. I will create this as a seperate issue to track on Github.

**Comment by sachs089** [comment]
@logicsandeep @eric-jahn @CTAJavier

**Comment by logicsandeep** [comment]
@sachs089  Please check and let me know I made sure the active_list view does not contain any null dedup_client_id and also made sure that we have more dedup_client_ids in the enrollment table.
