### ISSUE TITLE
Associate all completed survey submissions (existing and newly created surveys) to a global enrollment id

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#176]
All survey submissions must be associated with a global enrollment id (see https://github.com/servinglynk/hmis-lynk-open-source-docs/issues/113 ). Linking survey submissions to global enrollments and thus global projects (https://github.com/servinglynk/hmis-lynk-open-source-docs/issues/222 ) will allow client consent to function (issue https://github.com/servinglynk/hmis-lynk-open-source-docs/issues/345 enforces consent against a list of global project ids). This will require API implementation (CRUD methods) and documentation updates. 
These schema changes must also be synced to the data warehouse for reporting/analytics. Data must be populated for existing records.

**Comment by eric-jahn** [comment]
A survey can be created (from a bunch of questions) by anyone in a customer account (project *group* id).  A project group ID represents a single customer account, which is comprised of just a bunch of global projects.  Anyone in a project group ID can see the same surveys and they can add from that customer's set of surveys to their global project and thereby allow global enrollees in their project to take those surveys. The completed survey is associated with a global enrollment ID.  The blank survey snapshot, before anyone takes the survey, is associated with a global project id.

**Comment by suryayadavalli** [comment]
**Notes**
- Survey will be set up in the survey schema
- Clients will be surveyed and responses will be collected
- When these responses are submitted to HSLynk - we generate a submission ID (So, if the client is surveyed for Survey A 3 times , there will be 3 submission Ids).
- The goal is to associate these submissions with a global enrollment.
 
**Action Items**
Currently , we are not maintaining the association between client and submissions. However, to be able to associate a submission with a global-enrollment Id, we need modify existing Survey submission API to maintain this mapping.
Below is an example as to how the mapping should be maintained. (Lets call this entity SURVEY_SUBMISSION)


CLIENT _ID | SURVEY_ID | SUBMISSION_ID
-- | -- | --
CLIENT-1 | SURVEY-1 | SUB-1
CLIENT-1 | SURVEY-1 | SUB-2
CLIENT-1 | SURVEY-2 | SUB-3
CLIENT-1 | SURVEY-3 | SUB-4
CLIENT-2 | SURVEY-1 | SUB-5
CLIENT-2 | SURVEY-2 | SUB-6


 
Once this is complete, we need to associate these submissions with the global enrollments , using the **following steps.**
- GET All the survey submissions for a client _**(New API that needs to be implemented in survey micro service)**_
- GET All the global enrollments for a client _**(New API will be provided by HMIS global api micro service)**_
- UPDATE SURVEY_SUBMISSION with Global enrollment ID, that is selected **_(New API that needs to be implemented to associate submissions with global enrollments)._**

**Comment by suryayadavalli** [comment]
@gerardgaudry : for the first action item to create CLIENT_SURVEY_SUBMISSION , please look into the following components . I highlighted the code the piece code that will help with this.

https://github.com/hserv/coordinated-entry/blob/master/hmis-survey-api/src/main/java/com/servinglynk/hmis/warehouse/rest/ClientsControllerV3.java
**_This is the REST API the is called for posting responses. When this call is made the submission id will be generated._**
![image](https://user-images.githubusercontent.com/10738348/35138673-846cc758-fca4-11e7-8587-97317679ee0b.png)

https://github.com/hserv/coordinated-entry/blob/master/hmis-survey-api/src/main/java/com/servinglynk/hmis/warehouse/service/impl/ResponseServiceImplV3.java
_**You can see the submission ID is getting generated here and set up to each response. However, You we need to create a record now in CLIENT_SURVEY_SUBMISSION with client Id , survey id, submission id , (global enrollment id will be null at this time)**_
![image](https://user-images.githubusercontent.com/10738348/35138744-d02d1436-fca4-11e7-8b2e-49434d120e66.png)

**Comment by suryabi** [comment]
1. When the responses are submitted , we create an association between client , survey and submission
2.  To associate a global enrollment the following APIs will be called.
     _*(GET)* Fetch all submissions for a client - GET API to fetch the survey submissions for a client.
     *(GET)* Fetch all global enrollments for a client - Will be part of HSLynk API 
     *(PUT)* Update Client / Survey / Submission - to associate a client's survey submission with a global enrollment Id._

**Comment by suryayadavalli** [comment]
Commit Id :  https://github.com/hserv/coordinated-entry/commits/master

Documentation : https://hmis-api.github.io/survey-service-api/#clientsurveysubmissions__clientid_
