### ISSUE TITLE
Implement chronicity check using 2015 HMIS APIs for eligibility match

### ISSUE THREAD

**Issue by Dinesh846** [hserv/coordinated-entry#20]
Check chronicity as that is a weighted factor used to calculate the program types for which a client is eligible.  Depends on this issue being completed in HMISLynk: https://github.com/servinglynk/hmis-lynk-open-source-docs/issues/117 .

**Comment by eric-jahn** [comment]
This has been subsumed under the housing matcher general project eligibility functionality we have.
