### ISSUE TITLE
Utilize Global Household APIs to determine household type for eligibility

### ISSUE THREAD

**Issue by Dinesh846** [hserv/coordinated-entry#21]
To fetch details for a client if he is having a family with children or if they are group of adults, and then fetch inventory accordingly.  Global Household IDs are located here: https://anypoint.mulesoft.com/apiplatform/apis/#/portals/organizations/1d2d1eb1-46af-4ee8-aa04-bd79ed2764a3/apis/66146/versions/68740

**Comment by suryayadavalli** [comment]
Handled as part of house matching implementation
