### ISSUE TITLE
Handle eligibility criterion returned from Housing Inventory

### ISSUE THREAD

**Issue by Dinesh846** [hserv/coordinated-entry#22]
Now, housing inventory service doesn't have sufficient eligibility parameters, but they should be there, and once implemented they should be implemented in housing matching service;
UC1: Some inventories can be assigned only for families.
UC2: Some can be there for a specific age group.

So assign a unit to client accordingly.

**Comment by suryayadavalli** [comment]
Handled as part of house matching implementation.
