### ISSUE TITLE
add eligibility criteria to housing inventory implementation and API

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#23]
Currently ""familyUnit" is the only eligibility criterion.

**Comment by suryayadavalli** [comment]
[eligibility_requirement.xlsx](https://github.com/hserv/coordinated-entry/files/385126/eligibility_requirement.xlsx)

**Comment by CTAJavier** [comment]
[eligibility_requirement.xlsx](https://github.com/hserv/coordinated-entry/files/386700/eligibility_requirement.xlsx)

**Comment by CTAJavier** [comment]
[CES Eligibility - Intact Families.xlsx](https://github.com/hserv/coordinated-entry/files/386704/CES.Eligibility.-.Intact.Families.xlsx)
[CES Eligibility - Men in Transition.xlsx](https://github.com/hserv/coordinated-entry/files/386707/CES.Eligibility.-.Men.in.Transition.xlsx)
[CES Eligibility - Women in Transition.xlsx](https://github.com/hserv/coordinated-entry/files/386705/CES.Eligibility.-.Women.in.Transition.xlsx)
[Copy of CES Eligibility.xlsx](https://github.com/hserv/coordinated-entry/files/386706/Copy.of.CES.Eligibility.xlsx)
[CES Eligibility - All.xlsx](https://github.com/hserv/coordinated-entry/files/386708/CES.Eligibility.-.All.xlsx)
[CES Eligibility - Homeward Bound.xlsx](https://github.com/hserv/coordinated-entry/files/386709/CES.Eligibility.-.Homeward.Bound.xlsx)

**Comment by eric-jahn** [comment]
Can I go ahead and consolidate all these into tabs on a public google sheet?

**Comment by CTAJavier** [comment]
Yes

**Comment by eric-jahn** [comment]
Consolidated Google Sheet: https://docs.google.com/spreadsheets/d/1lDwnz4GXuIEvIL2bKdIZHcS4xbA6CB9v2yZZ5G263Vk/edit?usp=sharing  (@CTAJavier and @suryayadavalli can edit).  Please contact me if you need edit access.

**Comment by eric-jahn** [comment]
I believe these have been have hard-coded.

**Comment by eric-jahn** [comment]
@everyone: Can I close this issue if all the housing eligibility requirements have been hard-coded for Monterey?  I'll make a separate issue about dynamically programmable housing eligibility requirements, but that is not as urgent.

**Comment by eric-jahn** [comment]
created this issue to isolate the dynamic configuration aspect, so we can close this critical one faster.
