### ISSUE TITLE
Active List Changes

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#248]
changes to the API include, ability to submit a "bonus Score" and then the http get should show the Bonus score, the Vi Score(current score) and a Total Score, 

also need to be able to add notes when re-adding a client, currently we can only add a reason when we remove a client
related: https://github.com/servinglynk/hslynk-open-source-docs/issues/624
cc: @CTAJavier

**Comment by suryabi** [comment]
@eric, its 4 to 6 hours .

**Comment by suryayadavalli** [comment]
Working on this issue currently . Will deploy the changes by EOD tomorrow.

**Comment by suryayadavalli** [comment]
https://github.com/hserv/coordinated-entry/commit/7f3f364f24d3fe1eacdb8b5ac931a5f38dd92c6e
Complete and deployed in production.

**Comment by eric-jahn** [comment]
Documentation: https://api.hslynk.com/?urls.primaryName=Housing%20Match%20Service%20Api#/default/PUT_eligibleclients-dedupClientId
