### ISSUE TITLE
The survey upload creates responses with null question_id.

### ISSUE THREAD

**Issue by logicsandeep** [hserv/coordinated-entry#252]
The survey upload creates responses with null question_id.
cc: @CTAJavier

**Comment by CTAJavier** [comment]
to Clarify, when a survey response is submitted, The QuestionID and SectionID fields are null in the data warehouse. Doing a GET on the submission ID returns the entire submission including the QuestionID and the section ID

**Comment by CTAJavier** [comment]
Example POST 

I20181030-20:55:46.082(1)? info: Starting queue KddzvmNbA3sn6Sjki, 2 jobs
I20181030-20:55:46.091(1)? debug: HMIS API:get#31 (https://www.hmislynk.com/hmis-clientapi/rest/search/client?q=9b60cb11-5c3a-4d5b-942d-90dde4d5dc63&maxItems=2&sort=firstName&order=asc) 
I20181030-20:55:46.999(1)? debug: HMIS API:get#31 res (https://www.hmislynk.com/hmis-clientapi/rest/search/client?q=9b60cb11-5c3a-4d5b-942d-90dde4d5dc63&maxItems=2&sort=firstName&order=asc) 200
I20181030-20:55:47.000(1)? debug: 9b60cb11-5c3a-4d5b-942d-90dde4d5dc63 matched as 9b60cb11-5c3a-4d5b-942d-90dde4d5dc63
I20181030-20:55:47.002(1)? debug: HMIS API:post#32 https://www.hmislynk.com/survey-api/rest/clients/9b60cb11-5c3a-4d5b-942d-90dde4d5dc63/surveys/5bbef248-5627-466a-8a74-76e2d43763f0/responses 
I20181030-20:55:47.003(1)? { headers: 
I20181030-20:55:47.004(1)?    { 'X-HMIS-TrustedApp-Id': 'D097E5A2-DED7-44DB-A946-3A3DA8F5D3B1',
I20181030-20:55:47.004(1)?      Authorization: 'HMISUserAuth session_token=51BE50D0D8DD486EBABE8C6229E869B310F3114EBF3F4BC99B1EC20B154CED2F',
I20181030-20:55:47.004(1)?      Accept: 'application/json',
I20181030-20:55:47.005(1)?      'Content-Type': 'application/json' },
I20181030-20:55:47.005(1)?   data: 
I20181030-20:55:47.006(1)?    { responses: 
I20181030-20:55:47.006(1)?       { responses: 
I20181030-20:55:47.007(1)?          [ { questionId: '08b279e4-6dd9-4f38-accd-9efe5e63dc34',
I20181030-20:55:47.007(1)?              responseText: 'street',
I20181030-20:55:47.008(1)?              sectionId: '52986609-a1f0-4ed2-a499-d6d9fa724270' },
I20181030-20:55:47.008(1)?            { questionId: '53af6f40-80ef-42fa-8f86-103d02ec2c01',
I20181030-20:55:47.009(1)?              responseText: '8881',
I20181030-20:55:47.009(1)?              sectionId: '52986609-a1f0-4ed2-a499-d6d9fa724270' } ] } },
I20181030-20:55:47.009(1)?   correlationId: 32 }
I20181030-20:55:48.292(1)? debug: HMIS API:post#32 res (https://www.hmislynk.com/survey-api/rest/clients/9b60cb11-5c3a-4d5b-942d-90dde4d5dc63/surveys/5bbef248-5627-466a-8a74-76e2d43763f0/responses) 
I20181030-20:55:48.292(1)? { statusCode: 200,
I20181030-20:55:48.293(1)?   headers: 
I20181030-20:55:48.293(1)?    { 'content-type': 'application/json;charset=UTF-8',
I20181030-20:55:48.294(1)?      date: 'Tue, 30 Oct 2018 19:55:47 GMT',
I20181030-20:55:48.294(1)?      server: 'Apache',
I20181030-20:55:48.294(1)?      vary: 'Accept-Encoding',
I20181030-20:55:48.294(1)?      'content-length': '102',
I20181030-20:55:48.294(1)?      connection: 'Close' },
I20181030-20:55:48.295(1)?   data: 
I20181030-20:55:48.295(1)?    { response: 
I20181030-20:55:48.295(1)?       { questionScore: 0,
I20181030-20:55:48.296(1)?         refused: false,
I20181030-20:55:48.296(1)?         submissionId: '82e445f2-5926-461a-8412-f969425e34af' } } }
I20181030-20:55:48.297(1)? info: job succeeded AGmFu8ECYyJp9zTWY
I20181030-20:55:48.297(1)? debug: HMIS API:get#33 (https://www.hmislynk.com/hmis-clientapi/rest/search/client?q=9b60cb11-5c3a-4d5b-942d-90dde4d5dc63&maxItems=2&sort=firstName&order=asc) 
I20181030-20:55:49.334(1)? debug: HMIS API:get#33 res (https://www.hmislynk.com/hmis-clientapi/rest/search/client?q=9b60cb11-5c3a-4d5b-942d-90dde4d5dc63&maxItems=2&sort=firstName&order=asc) 200
I20181030-20:55:49.335(1)? debug: 9b60cb11-5c3a-4d5b-942d-90dde4d5dc63 matched as 9b60cb11-5c3a-4d5b-942d-90dde4d5dc63
I20181030-20:55:49.336(1)? debug: HMIS API:post#34 https://www.hmislynk.com/survey-api/rest/clients/9b60cb11-5c3a-4d5b-942d-90dde4d5dc63/surveys/5bbef248-5627-466a-8a74-76e2d43763f0/responses 
I20181030-20:55:49.336(1)? { headers: 
I20181030-20:55:49.337(1)?    { 'X-HMIS-TrustedApp-Id': 'D097E5A2-DED7-44DB-A946-3A3DA8F5D3B1',
I20181030-20:55:49.337(1)?      Authorization: 'HMISUserAuth session_token=51BE50D0D8DD486EBABE8C6229E869B310F3114EBF3F4BC99B1EC20B154CED2F',
I20181030-20:55:49.338(1)?      Accept: 'application/json',
I20181030-20:55:49.338(1)?      'Content-Type': 'application/json' },
I20181030-20:55:49.339(1)?   data: 
I20181030-20:55:49.339(1)?    { responses: 
I20181030-20:55:49.340(1)?       { responses: 
I20181030-20:55:49.340(1)?          [ { questionId: '08b279e4-6dd9-4f38-accd-9efe5e63dc34',
I20181030-20:55:49.341(1)?              responseText: 'MiniVan',
I20181030-20:55:49.341(1)?              sectionId: '52986609-a1f0-4ed2-a499-d6d9fa724270' },
I20181030-20:55:49.342(1)?            { questionId: '53af6f40-80ef-42fa-8f86-103d02ec2c01',
I20181030-20:55:49.342(1)?              responseText: '9991',
I20181030-20:55:49.342(1)?              sectionId: '52986609-a1f0-4ed2-a499-d6d9fa724270' } ] } },
I20181030-20:55:49.343(1)?   correlationId: 34 }
I20181030-20:55:50.564(1)? debug: HMIS API:post#34 res (https://www.hmislynk.com/survey-api/rest/clients/9b60cb11-5c3a-4d5b-942d-90dde4d5dc63/surveys/5bbef248-5627-466a-8a74-76e2d43763f0/responses) 
I20181030-20:55:50.565(1)? { statusCode: 200,
I20181030-20:55:50.566(1)?   headers: 
I20181030-20:55:50.567(1)?    { 'content-type': 'application/json;charset=UTF-8',
I20181030-20:55:50.567(1)?      date: 'Tue, 30 Oct 2018 19:55:50 GMT',
I20181030-20:55:50.568(1)?      server: 'Apache',
I20181030-20:55:50.569(1)?      vary: 'Accept-Encoding',
I20181030-20:55:50.569(1)?      'content-length': '102',
I20181030-20:55:50.570(1)?      connection: 'Close' },
I20181030-20:55:50.570(1)?   data: 
I20181030-20:55:50.572(1)?    { response: 
I20181030-20:55:50.573(1)?       { questionScore: 0,
I20181030-20:55:50.573(1)?         refused: false,
I20181030-20:55:50.574(1)?         submissionId: '3e8f544f-4109-47ef-9913-d1606fbe4773' } } }
I20181030-20:55:50.574(1)? info: job succeeded rJ6E6CMYbbzjKbEbS
I20181030-20:55:50.575(1)? info: Done processing queue KddzvmNbA3sn6Sjki

**Comment by CTAJavier** [comment]
`I20181030-20:55:46.082(1)? info: Starting queue KddzvmNbA3sn6Sjki, 2 jobs
I20181030-20:55:46.091(1)? debug: HMIS API:get#31 (https://www.hmislynk.com/hmis-clientapi/rest/search/client?q=9b60cb11-5c3a-4d5b-942d-90dde4d5dc63&maxItems=2&sort=firstName&order=asc) 
I20181030-20:55:46.999(1)? debug: HMIS API:get#31 res (https://www.hmislynk.com/hmis-clientapi/rest/search/client?q=9b60cb11-5c3a-4d5b-942d-90dde4d5dc63&maxItems=2&sort=firstName&order=asc) 200
I20181030-20:55:47.000(1)? debug: 9b60cb11-5c3a-4d5b-942d-90dde4d5dc63 matched as 9b60cb11-5c3a-4d5b-942d-90dde4d5dc63
I20181030-20:55:47.002(1)? debug: HMIS API:post#32 https://www.hmislynk.com/survey-api/rest/clients/9b60cb11-5c3a-4d5b-942d-90dde4d5dc63/surveys/5bbef248-5627-466a-8a74-76e2d43763f0/responses 
I20181030-20:55:47.003(1)? { headers: 
I20181030-20:55:47.004(1)?    { 'X-HMIS-TrustedApp-Id': 'D097E5A2-DED7-44DB-A946-3A3DA8F5D3B1',
I20181030-20:55:47.004(1)?      Authorization: 'HMISUserAuth session_token=51BE50D0D8DD486EBABE8C6229E869B310F3114EBF3F4BC99B1EC20B154CED2F',
I20181030-20:55:47.004(1)?      Accept: 'application/json',
I20181030-20:55:47.005(1)?      'Content-Type': 'application/json' },
I20181030-20:55:47.005(1)?   data: 
I20181030-20:55:47.006(1)?    { responses: 
I20181030-20:55:47.006(1)?       { responses: 
I20181030-20:55:47.007(1)?          [ { questionId: '08b279e4-6dd9-4f38-accd-9efe5e63dc34',
I20181030-20:55:47.007(1)?              responseText: 'street',
I20181030-20:55:47.008(1)?              sectionId: '52986609-a1f0-4ed2-a499-d6d9fa724270' },
I20181030-20:55:47.008(1)?            { questionId: '53af6f40-80ef-42fa-8f86-103d02ec2c01',
I20181030-20:55:47.009(1)?              responseText: '8881',
I20181030-20:55:47.009(1)?              sectionId: '52986609-a1f0-4ed2-a499-d6d9fa724270' } ] } },
I20181030-20:55:47.009(1)?   correlationId: 32 }
I20181030-20:55:48.292(1)? debug: HMIS API:post#32 res (https://www.hmislynk.com/survey-api/rest/clients/9b60cb11-5c3a-4d5b-942d-90dde4d5dc63/surveys/5bbef248-5627-466a-8a74-76e2d43763f0/responses) 
I20181030-20:55:48.292(1)? { statusCode: 200,
I20181030-20:55:48.293(1)?   headers: 
I20181030-20:55:48.293(1)?    { 'content-type': 'application/json;charset=UTF-8',
I20181030-20:55:48.294(1)?      date: 'Tue, 30 Oct 2018 19:55:47 GMT',
I20181030-20:55:48.294(1)?      server: 'Apache',
I20181030-20:55:48.294(1)?      vary: 'Accept-Encoding',
I20181030-20:55:48.294(1)?      'content-length': '102',
I20181030-20:55:48.294(1)?      connection: 'Close' },
I20181030-20:55:48.295(1)?   data: 
I20181030-20:55:48.295(1)?    { response: 
I20181030-20:55:48.295(1)?       { questionScore: 0,
I20181030-20:55:48.296(1)?         refused: false,
I20181030-20:55:48.296(1)?         submissionId: '82e445f2-5926-461a-8412-f969425e34af' } } }
I20181030-20:55:48.297(1)? info: job succeeded AGmFu8ECYyJp9zTWY
I20181030-20:55:48.297(1)? debug: HMIS API:get#33 (https://www.hmislynk.com/hmis-clientapi/rest/search/client?q=9b60cb11-5c3a-4d5b-942d-90dde4d5dc63&maxItems=2&sort=firstName&order=asc) 
I20181030-20:55:49.334(1)? debug: HMIS API:get#33 res (https://www.hmislynk.com/hmis-clientapi/rest/search/client?q=9b60cb11-5c3a-4d5b-942d-90dde4d5dc63&maxItems=2&sort=firstName&order=asc) 200
I20181030-20:55:49.335(1)? debug: 9b60cb11-5c3a-4d5b-942d-90dde4d5dc63 matched as 9b60cb11-5c3a-4d5b-942d-90dde4d5dc63
I20181030-20:55:49.336(1)? debug: HMIS API:post#34 https://www.hmislynk.com/survey-api/rest/clients/9b60cb11-5c3a-4d5b-942d-90dde4d5dc63/surveys/5bbef248-5627-466a-8a74-76e2d43763f0/responses 
I20181030-20:55:49.336(1)? { headers: 
I20181030-20:55:49.337(1)?    { 'X-HMIS-TrustedApp-Id': 'D097E5A2-DED7-44DB-A946-3A3DA8F5D3B1',
I20181030-20:55:49.337(1)?      Authorization: 'HMISUserAuth session_token=51BE50D0D8DD486EBABE8C6229E869B310F3114EBF3F4BC99B1EC20B154CED2F',
I20181030-20:55:49.338(1)?      Accept: 'application/json',
I20181030-20:55:49.338(1)?      'Content-Type': 'application/json' },
I20181030-20:55:49.339(1)?   data: 
I20181030-20:55:49.339(1)?    { responses: 
I20181030-20:55:49.340(1)?       { responses: 
I20181030-20:55:49.340(1)?          [ { questionId: '08b279e4-6dd9-4f38-accd-9efe5e63dc34',
I20181030-20:55:49.341(1)?              responseText: 'MiniVan',
I20181030-20:55:49.341(1)?              sectionId: '52986609-a1f0-4ed2-a499-d6d9fa724270' },
I20181030-20:55:49.342(1)?            { questionId: '53af6f40-80ef-42fa-8f86-103d02ec2c01',
I20181030-20:55:49.342(1)?              responseText: '9991',
I20181030-20:55:49.342(1)?              sectionId: '52986609-a1f0-4ed2-a499-d6d9fa724270' } ] } },
I20181030-20:55:49.343(1)?   correlationId: 34 }
I20181030-20:55:50.564(1)? debug: HMIS API:post#34 res (https://www.hmislynk.com/survey-api/rest/clients/9b60cb11-5c3a-4d5b-942d-90dde4d5dc63/surveys/5bbef248-5627-466a-8a74-76e2d43763f0/responses) 
I20181030-20:55:50.565(1)? { statusCode: 200,
I20181030-20:55:50.566(1)?   headers: 
I20181030-20:55:50.567(1)?    { 'content-type': 'application/json;charset=UTF-8',
I20181030-20:55:50.567(1)?      date: 'Tue, 30 Oct 2018 19:55:50 GMT',
I20181030-20:55:50.568(1)?      server: 'Apache',
I20181030-20:55:50.569(1)?      vary: 'Accept-Encoding',
I20181030-20:55:50.569(1)?      'content-length': '102',
I20181030-20:55:50.570(1)?      connection: 'Close' },
I20181030-20:55:50.570(1)?   data: 
I20181030-20:55:50.572(1)?    { response: 
I20181030-20:55:50.573(1)?       { questionScore: 0,
I20181030-20:55:50.573(1)?         refused: false,
I20181030-20:55:50.574(1)?         submissionId: '3e8f544f-4109-47ef-9913-d1606fbe4773' } } }
I20181030-20:55:50.574(1)? info: job succeeded rJ6E6CMYbbzjKbEbS
I20181030-20:55:50.575(1)? info: Done processing queue KddzvmNbA3sn6Sjki
`

**Comment by CTAJavier** [comment]
Response 

{
    "responses": {
        "pagination": {
            "from": 0,
            "returned": 2,
            "total": 2,
            "maximum": 30,
            "sort": {}
        },
        "responses": [
            {
                "responseId": "a580d5f4-92df-44d0-b7a3-33ba1bd59cb1",
                "responseText": "MiniVan",
                "questionScore": 0,
                "clientId": "5888ce37-d3a3-46ae-bc6f-509750cc00b7",
                "dedupClientId": "75fc9cc0-c23a-11e6-bdda-06c37be0e663",
                "surveyId": "5bbef248-5627-466a-8a74-76e2d43763f0",
                "refused": false,
                "submissionId": "3e8f544f-4109-47ef-9913-d1606fbe4773"
            },
            {
                "responseId": "34c0cd98-1373-462e-9d73-95957b1c3746",
                "responseText": "9991",
                "questionScore": 0,
                "clientId": "5888ce37-d3a3-46ae-bc6f-509750cc00b7",
                "dedupClientId": "75fc9cc0-c23a-11e6-bdda-06c37be0e663",
                "surveyId": "5bbef248-5627-466a-8a74-76e2d43763f0",
                "refused": false,
                "submissionId": "3e8f544f-4109-47ef-9913-d1606fbe4773"
            }
        ]
    }
}
