### ISSUE TITLE
survey upload script

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#257]
# Requirements:
 * Upload efforts and ROS .csv files
       a) Get deduped client based on first name, last name and ssn.
   b) Create a deduped client if a client does not exist for FN,LN and SSN.
   c) Get existing case workers Id based on their FN and LN and associate it to the survey response.
  d) Create a new case worker if one does not match with the FN,LN combination to associate to a survey response.
  e) Look into the mapping document to map correct category which matches the ROS data standards. 

 * Upload .xlsx ROS file
 * On-going .xlsx uploads needed?  Need feedback.

# Deliverables:
 * User match handling algorithm:
   * First check if case worker in data file exists
     * If exists, then append data under this user, not touching the user's active status in either direction
     * If doesn't exist, create a new user for that case worker and make them inactive by default. 
 * Preliminary client match report, before committing the changes to the production database.
 * Preliminary user/caseworker match report for approval by Skid Row, before committing the changes to the production database.

**Comment by logicsandeep** [comment]
this issue is closed.
https://github.com/servinglynk/hslynk-open-source/tree/master/hmis-ces-onboarding
