### ISSUE TITLE
Modify Query options and add sorting parameters for getting client submissions

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#265]
This call currently gets all submissions for a client but Query parameters are currently required, This needs to be optional so we can send an empty request which returns all submissions for all clients (paginated) sorted by a parameter of our choosing,
Ideally default should be soft by date starting from latest going to oldest
Sorting params, would be date Ascending, Date descending, client name, survey name, survey id.
Also, update to up to 100 results per page
Calls Affected
![3](https://user-images.githubusercontent.com/4115079/54428246-31677c00-471d-11e9-9ee6-075412779855.png)

cc: @CTAJavier

**Comment by suryayadavalli** [comment]
Resolved. 

- Pagination limit was set to 100
- Sorting was provided for the following attributes - surveyName, surveyId, client name and date

https://api.hslynk.com/?urls.primaryName=Survey%20Service%20Api#/default/GET_clientsurveysubmissions

Commit id #
https://github.com/hserv/coordinated-entry/commit/7ac8a002e460d1e607fa67f3fd6e4858a7428dd4
