### ISSUE TITLE
Modify/add query parameters, and sorting for client submissions

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#266]
Currently, the call below returns a list of all of the submissions for a clientId this needs to be updated to either accept a clientID or DedupeID, 
A query parameter is necessary so we could search the submissions by survey ID or name, and sort by surveyId or by date without having to load all of the submissions and then sort/search on the client side
We see there is a sort:{} parameter but it is not clear what the options are, please clarify this.
Call affected
![4](https://user-images.githubusercontent.com/4115079/54428341-84413380-471d-11e9-907e-52779e79e16e.png)

cc: @CTAJavier

**Comment by suryayadavalli** [comment]
Resolved.
- Enabled API to support both client Id and dedupId
- Search by suveryId and survey name (surveyTitle )
- Sort by Survey Name (surveyTitle), Survey Id

https://api.hslynk.com/?urls.primaryName=Survey%20Service%20Api#/default/GET_clientsurveysubmissions-clientId

Commit #
https://github.com/hserv/coordinated-entry/commit/0e4b9ee2c4b1dac0245fe8dc5549abc327c40860
