### ISSUE TITLE
Any call returning client data should include the schema (year) for the client if any

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#267]
ie , if we hit /clientsurveysubmission/clientId  and we get this response 
{
        "id": "e67bb703-bce1-49b0-948d-75f286f4497b",
        "clientId": "035c313e-a39d-4098-bf89-544b553d752f",
        "surveyId": "57dbe6b2-83a9-4a8b-b4aa-65985241d341",
        "submissionId": "d89ac01a-32a4-4530-92a6-d59b161b5ca8",
        "globalEnrollmentId": "e166faae-1661-49ab-9987-4f66fd982cb2",
        "client": {
          "id": "035c313e-a39d-4098-bf89-544b553d752f",
          "firstName": "Ryan",
          "middleName": "",
          "lastName": "Peterson",
          "dob": 339989400000,
          "dedupClientId": "5dfe2ac2-43af-4d6d-9ee8-0e8fac5e3eg8"
        } 
Should instead return 
{
        "id": "e67bb703-bce1-49b0-948d-75f286f4497b",
        "clientId": "035c313e-a39d-4098-bf89-544b553d752f",
        "surveyId": "57dbe6b2-83a9-4a8b-b4aa-65985241d341",
        "submissionId": "d89ac01a-32a4-4530-92a6-d59b161b5ca8",
        "globalEnrollmentId": "e166faae-1661-49ab-9987-4f66fd982cb2",
        "client": {
        "id": "035c313e-a39d-4098-bf89-544b553d752f",
               “schema”: “v2017”,
          	  "firstName": "Ryan",
               "middleName": "",
          	  "lastName": "Peterson",
               "dob": 339989400000,
               "dedupClientId": "5dfe2ac2-43af-4d6d-9ee8-0e8fac5e3eg8"
        }
cc: @CTAJavier

**Comment by suryayadavalli** [comment]
The **href** link for client is included that contains the schema year.
Sample response is included in the API documentation.
https://api.hslynk.com/?urls.primaryName=Survey%20Service%20Api#/default/GET_clientsurveysubmissions-clientId

Commit Id #
https://github.com/hserv/coordinated-entry/commit/0e4b9ee2c4b1dac0245fe8dc5549abc327c40860

**Comment by eric-jahn** [comment]
@CTAJavier @pgorecki : Does this resolve the issue for you?

**Comment by eric-jahn** [comment]
Looks like you have to parse it out of the client link: / hmis-clientapi / rest / v2014 / clients / 51d496ac-e22b-4505-ac4b-45fdd74b3d70".  Is that too inconvenient, or is that ok?

**Comment by pgorecki** [comment]
That's not convenient but it's good enough.
