### ISSUE TITLE
Dates should be included in any call referencing a submissionId

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#268]
Currently, we have to make additional calls to get a date for a submission, this means we would double the calls needed if we  used this call  /clientsurveysubmission/clientId, we would need to make another call for each submission ID to get the date from the responses since it is not included in the submission definition.

**Comment by suryayadavalli** [comment]
**submissionDate** is included in the response.
Note : effectiveDate for a submission is considered as submissionDate. If the effective date for a submission is NULL, then the score's submission date is considered as the submissionDate 
API documentation
https://api.hslynk.com/?urls.primaryName=Survey%20Service%20Api#/default/GET_clientsurveysubmissions-clientId

Commit # 
https://github.com/hserv/coordinated-entry/commit/0e4b9ee2c4b1dac0245fe8dc5549abc327c40860

**Comment by pgorecki** [comment]
I don't see any dates in the response:
![obraz](https://user-images.githubusercontent.com/636023/60086148-dc36ff80-973a-11e9-9800-add7e56a6b06.png)

**Comment by eric-jahn** [comment]
per Surya, there is old data (prior to the addition of a rule to use as a proxy, the scoring date, when effective date is not present) which doesn't yet use the proxy date.  So for these old records, no date is returned yet.
