### ISSUE TITLE
it is still possible to get a deleted submission

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#281]
when deleting submission, we get 204 as a result. After deletion it is still possible to get the deleted submission (using GET request), but this time it has 0 responses, i. e.:
deleted https://www.hmislynk.com/survey-api/rest/clients/b4f57077-fc53-47c3-9445-bb3c86f223a7/surveys/543bbdd1-2cb3-48f9-ba3e-7aa25edf1daa/submissions/c0e2dca1-79ba-47d8-8e19-f72fba4ef98f results in:
```{
    "responses": {
        "pagination": {
            "from": 0,
            "returned": 0,
            "total": 0,
            "maximum": 30,
            "sort": {}
        },
        "responses": []
    }
}```
looks like you are deleting all responses tied to a submission but not a submission object itself

**Comment by eric-jahn** [comment]
cc: @pgorecki

**Comment by suryayadavalli** [comment]
commit id:  https://github.com/hserv/coordinated-entry/commit/23474e5b60dcef1dbc3974e87bafe3656e4cb25a

**Comment by suryayadavalli** [comment]
Resolved. Closing the issue.
