### ISSUE TITLE
 it is possible to get the nonexistent submission

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#282]
@pgorecki : I've managed to make a successful GET to non-existing submission: https://www.hmislynk.com/survey-api/rest/clients/b4f57077-fc53-47c3-9445-bb3c86f223a7/surveys/412aca65-6098-43f8-97c6-7c3dd3bdb45e/submissions/00000000-0000-0000-0000-000000000000

**Comment by suryayadavalli** [comment]
commit id: https://github.com/hserv/coordinated-entry/commit/23474e5b60dcef1dbc3974e87bafe3656e4cb25a

**Comment by suryayadavalli** [comment]
Resolved, Closing the issue
