### ISSUE TITLE
`questionId` is missing from GET survey submissions response

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#285]
https://api.hslynk.com/?urls.primaryName=Survey%20Service%20Api#/default/GET_v3-clients-dedupclientid-surveys-surveyid-submissions-submissionid

private ref: https://hslynk.slack.com/archives/CAA3H13SA/p1557143766100800

cc: @pgorecki

**Comment by suryabi** [comment]
The responses for this submission do not have question ids.  Attached is the data (masked few pieces of information).

![image](https://user-images.githubusercontent.com/19498132/58600588-14c9e300-823a-11e9-9bcf-7d8d7a282dc3.png)

**Comment by eric-jahn** [comment]
Shouldn't it return the field with null value as positive confirmation there is no question id for this response?  That way, they can always expect question id as a key, but perhaps without a value?

**Comment by suryayadavalli** [comment]
@ericjahn : We don't' return any elements that carry NULL values, for any APIs, across the platform - as a standard.

**Comment by eric-jahn** [comment]
Okay, then a response schema with 'optional' for response ID would help people know what to expect. I created: https://github.com/hmis-api/survey-service-api/issues/7

**Comment by pgorecki** [comment]
how is it possible that you have a response and you don't know for which question is it. This makes the response useless.

**Comment by eric-jahn** [comment]
@suryayadavalli: Was the questionid ever deleted, thereby orphaning the response?

**Comment by suryayadavalli** [comment]
@pgorecki : Can you confirm that for the specific submission that has an issue, if the question Ids were sent from your end ? I spent decent time to figure out if there is any issue on our end. I see few submissions with question Ids and few submissions without question ids. I am still checking if question is sent to us and ignored, but close enough to rule out that, that is the case.

**Comment by suryayadavalli** [comment]
@pgorecki : Also, can you please go through the thread below where we discussed regarding the question Ids 

https://hslynk.slack.com/archives/CAA3H13SA/p1535360559000100 

As part of V3 API implementation we disabled for the check for questionIds (based on what we discussed then, to accommodate your requirements). 

Secondly, I was looking at the  survey definition for one of the surveys I randomly picked up (**0c557cc7-16d6-4995-b42c-ee6403cb02c0**)  and looks like not all the questions in the survey definition carry question Id.  Not sure, if I am missing some thing here but can you explain this ?

![image](https://user-images.githubusercontent.com/10738348/58722539-874ad800-838c-11e9-8fbe-4c44adbc2759.png)

Once we exchange more information about this issue and figure out what exactly is happening here, we can agree upon the need to enforce the questionId back.

**Comment by eric-jahn** [comment]
I also think that we should use the label questionID, instead of hmisID, since not all questions are related to hmis.

**Comment by pgorecki** [comment]
We never intended to post responses without providing questionIds. During a survey creation process (i.e. when creating/editing a survey) our code checks if all question items in the definition have associated questionIds (hmisIds) and new questions are created if necessary. Therefore, when a survey submission is uploaded to HSLYNK, all required questionIds are in the definition. Anyway, I've added an extra assertion check on our side just to make sure.

I'm not sure about survey 0c557cc7-16d6-4995-b42c-ee6403cb02c0 - I am unable to check it because both apis (V2 and V3) return 404. I tried the following urls: https://www.hslynk.com/survey-api/rest/v2/surveys/0c557cc7-16d6-4995-b42c-ee6403cb02c0 and https://www.hslynk.com/survey-api/rest/v3/surveys/0c557cc7-16d6-4995-b42c-ee6403cb02c0. The screenshot contains only 4 lines so it's hard for me to tell what's going on in there. Maybe this is an old survey that was created during development of the survey upload code? Or maybe you were looking at a non-question item?

The issue you mentioned in the archives was related to the fact that we wanted to reuse questionIds between different project groups. This was needed for implementing enrollment surveys - we wanted to share the same enrollment questions across different organizations. It turns out that you solved it by disabling questionId check entirely, I think the better approach would be to check if questionId is valid uuid.

**Comment by eric-jahn** [comment]
Thank you @pgorecki .  That helps.  I'm also going to ask @suryayadavalli to change hmisID to questionID with this new version, because it is misleading to users of the API.

**Comment by pgorecki** [comment]
@eric-jahn `hmisId` is the name that we are using internally within a survey definition, so I don't see any reason for you to change it.

@suryabi here are some more details for the problem:
```
2019-06-03T13:42:54.534Z - debug: HMIS API:post#75 https://www.hmislynk.com/survey-api/rest/clients/b4f57077-fc53-47c3-9445-bb3c86f223a7/surveys/5bbef248-5627-466a-8a74-76e2d43763f0/responses 
{ headers: 
   { 'X-HMIS-TrustedApp-Id': '16631CFE-6909-4AC1-B4EB-57902AC7AF0A',
     Authorization: 'HMISUserAuth session_token=7275564A83784EA9B98834B2FC0DBBB5D61C1A4F6A5147C88EAB5D40D1595E3A',
     Accept: 'application/json',
     'Content-Type': 'application/json' },
  data: 
   { responses: 
      { responses: 
         [ { id: 'question1',
             questionId: '007f9b45-b990-4717-9c8f-83e37588c941',
             responseText: '1',
             sectionId: '26f7ca83-b667-4601-ba0a-3dbd17dc0980' },
           { id: 'question2',
             questionId: 'd5a93c67-b826-43d1-ac90-031ecfc8b5dd',
             responseText: '2',
             sectionId: '26f7ca83-b667-4601-ba0a-3dbd17dc0980' } ] } },
  correlationId: 75 }

2019-06-03T13:42:55.539Z - debug: HMIS API:post#75 res (https://www.hmislynk.com/survey-api/rest/clients/b4f57077-fc53-47c3-9445-bb3c86f223a7/surveys/5bbef248-5627-466a-8a74-76e2d43763f0/responses)
{ statusCode: 200,
  headers: 
   { 'access-control-allow-headers': '*',
     'access-control-allow-origin': '*',
     'content-type': 'application/json;charset=UTF-8',
     date: 'Mon, 03 Jun 2019 13:42:55 GMT',
     server: 'Apache-Coyote/1.1',
     vary: 'Accept-Encoding',
     'x-hmis-trustedapp-id': '*',
     'content-length': '102',
     connection: 'Close' },
  data: 
   { response: 
      { questionScore: 0,
        refused: false,
        submissionId: '8957b603-6ebd-4b44-84d5-3ce00133f17f' } } }
```
As you see, I am submitting 2 responses here and I'm getting submissionId. However, when GETtting this submission, I don't see questionIds in a response:
![image](https://user-images.githubusercontent.com/636023/58807077-b2952780-8617-11e9-9269-c54e4a760394.png)

**Comment by eric-jahn** [comment]
@pgorecki understood.  Not sure why HOME App calls it that, either.  It's really confusing (and incorrectly named even) for new developers/apps though, so we have to change it on our side.

**Comment by eric-jahn** [comment]
@pgorecki : Surya explained to me that the hmisID is a label you guys store, and not defined on our side, so no need to change anything.  Sorry about that.

**Comment by suryayadavalli** [comment]
@pgorecki : 

**Question Ids' in the request body above** 
![image](https://user-images.githubusercontent.com/10738348/58875696-1a338d00-8681-11e9-8342-593b880a901a.png)

Both the questions, in your requests belong to the project group : "**MO0010**"

**However,** 
Survey '"5bbef248-5627-466a-8a74-76e2d43763f0" belongs to ""HO0002"

Based on the session token in the request body above
Logged user belongs to the project group : ""HO0002"

You cannot use the questions that belong to one project group from other project group. Technically, the question doesn't exist in the context of the logger in user, so it's not mapped to the response.

**Comment by eric-jahn** [comment]
@suryayadavalli So how does the client app know that the questionID/hmisID is invalid and not going to be mapped to a response?  As I understand it, we do no validation, so we wouldn't know either.  Is there a way we can throw an invalid questionID error response so the client knows this is happening?

**Comment by suryabi** [comment]
@eric-jahn : Client APP knows the question Ids that belong to the project group, the user logged in with.

No validation on HMIS end means "we accept the responses even if the question ID is null or if the passed in question ID doesn't exist".

If the question Id is present - we store the question Id- on the condition that it exists and belong to the project group.  We cannot just accept a project group to be using other question ids , for security purposes.

Both the questions above are dated 2016 and created by Udit (earlier developer for HOME). I am assuming these calls above are made for testing purposes.  @pgorecki can confirm.

**Comment by eric-jahn** [comment]
I'm going to close this due to inactivity.  We can reopen if there are requested behavior changes, but so far, current functionality appears to be reasonable.
