### ISSUE TITLE
DELETE survey/submission API fixes

### ISSUE THREAD

**Issue by logicsandeep** [hserv/coordinated-entry#286]
1)  Return a 200 HTTP status when delete survey/survey submissions. The documentation says We return 200, but the code returns a 204.

2) Delete Client_survey_submission when a DELETE /clients/{clientid}/surveys/{surveyid}/submissions/{submissionid} is called.

**Comment by suryayadavalli** [comment]
Issue #1 is addressed (update to API documentation).
Return a 200 HTTP status when delete survey/survey submissions. The documentation says We return 200, but the code returns a 204.
https://github.com/hmis-api/survey-service-api/commit/cb47581b2c69004bdae5360d4285bb0a44e0399f

Working on issue #2.

**Comment by suryayadavalli** [comment]
commit id : https://github.com/hserv/coordinated-entry/commit/cd991d7b6e2bd0b778cf12e16306745332913e49
