### ISSUE TITLE
eligibleclients API do not support dedupID

### ISSUE THREAD

**Issue by suryayadavalli** [hserv/coordinated-entry#293]
CC : @CTAJavier 

From @CTAJavier : eligibleclients/{client ID} endpoint only supports client ID, wasn't all the Survey stuff supposed to support dedupeClientID so shouldn't there be an eligibleclients/{dedupeClientId}

V3 is dedup Client ID, and it does not make sense to store Bonus scores under client ID if we are going to be posting scores for dedup client ID

**Comment by eric-jahn** [comment]
here is v3 which uses client dedupe id: https://api.hslynk.com/?urls.primaryName=Housing%20Match%20Service%20Api#/default/GET_eligibleclients_dedupid

**Comment by CTAJavier** [comment]
@eric-jahn  

Reopening this issue because the endpoint you listed  https://api.hslynk.com/?urls.primaryName=Housing%20Match%20Service%20Api#/default/GET_eligibleclients_dedupid is only for GET 
There is PUT but it's not V3, and the documentation is conflicting so I wanted to make sure this endpoint will accept a dedupeID https://api.hslynk.com/?urls.primaryName=Housing%20Match%20Service%20Api#/default/PUT_eligibleclients-dedupClientId,

![image](https://user-images.githubusercontent.com/14897073/72482052-3a97fe00-37b1-11ea-8552-f2b6243eb7b9.png)

**Comment by suryajaitra** [comment]
I will look into this issue and update by EOD today. Thanks !
cc @CTAJavier

**Comment by suryayadavalli** [comment]
I will check this issue and provide an update by EOD. Thanks !

CC @CTAJavier

**Comment by eric-jahn** [comment]
Is this issue resolved, and if so, what was the resolution?

**Comment by CTAJavier** [comment]
@eric-jahn This has not been resolved yet.

**Comment by suryayadavalli** [comment]
Documentation is missing for these APIs. Please find the updated documentation here. Will verify these APIs via automated tests and update the ticket again tonight.

API documentation link : https://docs.hslynk.com/?urls.primaryName=Housing%20Match%20Service%20Api#/default/GET_v3_eligibleclients-dedupClientId

**Comment by suryayadavalli** [comment]
please find the documentation for other APIs here
Get all eligible clients  https://docs.hslynk.com/?urls.primaryName=Housing%20Match%20Service%20Api#/default/GET_eligibleclients

Get eligible client by dedupId https://docs.hslynk.com/?urls.primaryName=Housing%20Match%20Service%20Api#/default/GET_eligibleclients_dedupid

POST eligible client  https://docs.hslynk.com/?urls.primaryName=Housing%20Match%20Service%20Api#/default/POST_eligibleclients

PUT eligible client  https://docs.hslynk.com/?urls.primaryName=Housing%20Match%20Service%20Api#/default/PUT_v3_eligibleclients-dedupClientId

Delete eligible client by dedupId https://docs.hslynk.com/?urls.primaryName=Housing%20Match%20Service%20Api#/default/DELETE_v3_eligibleclients-dedupClientId

**Comment by eric-jahn** [comment]
@CTAJavier Are the endpoints and documentation correct now?

**Comment by CTAJavier** [comment]
@eric-jahn It seems to be correct. @pgorecki will be working on this tonight, he will update if there's something that doesn't work as expected.
