### ISSUE TITLE
Attach enrollment ID feature is not available any more

### ISSUE THREAD

**Issue by suryayadavalli** [hserv/coordinated-entry#294]
From @CTAJavier 
/v3/clients/{dedupclientid}/surveys/{surveyid}/responses i remember we had the ability to attach an enrollment/generic enrollment ID, and i don't see it now, what this removed, if not how do we do it ?

**Comment by suryayadavalli** [comment]
Here is the API we have for attaching global enrollment for a submission.  It's a two step process

1) GET client survey submissions using https://api.hslynk.com/?urls.primaryName=Survey%20Service%20Api#/default/GET_clientsurveysubmissions-clientId and
2)  Associate the global enrollment Id with the client survey submission using.

https://api.hslynk.com/?urls.primaryName=Survey%20Service%20Api#/default/PUT_clientsurveysubmissions-clientSurveySubmissionId

**Comment by eric-jahn** [comment]
cc: @CTAJavier instructions above
