### ISSUE TITLE
API supporting DedupId /clientsurveysubmissions/{clientId} is not available

### ISSUE THREAD

**Issue by suryayadavalli** [hserv/coordinated-entry#295]

**Comment by eric-jahn** [comment]
By not available, does that mean it's not working, or that the clientID it uses is not the global client ID? What ID would it use otherwise, since I thought surveys just uses global IDs, and there was no version specific survey client ID?

**Comment by eric-jahn** [comment]
cc: @CTAJavier

**Comment by eric-jahn** [comment]
@suryayadavalli can we close this?

**Comment by eric-jahn** [comment]
needs more info to keep open
