### ISSUE TITLE
picklist values not referenced in the response

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#30]
[originally submitted by @CTAJavier in issue #29 ]
Why are picklist values not referenced in the response ?
What is the point of the pick lists if they actual response does not reference them? Does it really store the actual text submitted? We do not have a picklist table we are storing our picklist values as an array within our question table. We can work with this but just wondering why you have separate picklist tables instead of handling things with arrays as we do.

![https://github.com/hserv/coordinated-entry/blob/master/hmis-survey-api/doc/Survey%20ERD.png?raw=true](https://github.com/hserv/coordinated-entry/blob/master/hmis-survey-api/doc/Survey%20ERD.png?raw=true)

**Comment by eric-jahn** [comment]
[response from Surya]
regarding 30- i beleive its more of a question than issue . We associate picklist groups to questions and each picklist group is associted with a child collection of picklist ids . To their question , as to why we are noy maintaining IDs in responses  is to be able to run the expression evaluator for the score calculation. if you remember our conversation earlier , these responses should be compared against certain expression (race is hispanic && income > 25000) etc to get a score . for us to be able to do the evaluation we are capturing the responses as is.

**Comment by suryayadavalli** [comment]
Here is the proposal to include picklist code in the response.  In addition to the responseText (which contains Picklist code - in case the question type is not freefrom text), the API will also include the picklist element information related to each response. 

`{
   "responses":[
      {
         "responseId":"5f7f28b0-ed97-4571-a4bb-480d673e8bca",
         "responseText":"csacsc",
         "questionScore":1
      },
      {
         "responseId":"5f7f28b0-ed97-4571-a4bb-480d673e8bca",
         "responseText":"1,2",
         "questionScore":2,
         "pickListValues":[
            {
               "pickListValueId":"eff61efc-edcf-44d1-989b-452463d17db2",
               "pickListValueCode":"1",
               "valueText":"Test"
            },
            {
               "pickListValueId":"7b620bb1-007c-494a-aa3a-a5ff249f94d5",
               "pickListValueCode":"2",
               "valueText":"Test 2"
            }
         ]
      }
   ]
}`

in the example above,  response Id 5f7f28b0-ed97-4571-a4bb-480d673e8bca is a multi select response so, the responseText contains two picklist codes followed by the detail about each of these picklist code.

**Comment by CTAJavier** [comment]
with all the changes that need to be coded and the short timeline, can we close this issue for now and come back to it at a later time if it is still a pressing issue? at this point it will be faster for udit to code to the exiting api requirements than to wait for everything to get coded. Thanks

**Comment by eric-jahn** [comment]
okay, that works
