### ISSUE TITLE
The PUT/GET /matches/client/{dedupclientid}/status returned a 404 and /matches/client/{clientid}/status worked correctly

### ISSUE THREAD

**Issue by logicsandeep** [hserv/coordinated-entry#386]
The PUT /matches/client/{dedupclientid}/status returned a 404 and /matches/client/{clientid}/status worked correctly.

Change the API documentation and proper verification. If the clientid is used for the match then we need to update the documentation with the correct attribute.

API:
https://api.hslynk.com//house-matching-api/matches/client/ec49c900-f8ad-11e9-a57b-02fe61f7863e/status
Body:
{
  "status": "1",
  "comments": "testing",
  "recipients": {
    "toRecipients": [
      "Sandeep.Dolia@gmail.com"
    ],
    "bccRecipients": [
      "Sandeep.Dolia@gmail.com"
    ],
    "ccRecipients": [
      "Sandeep.Dolia@gmail.com"
    ]
  }
}

Returns: a 404

{
"error": [
  {
"code": "RESOURCE_NOT_FOUND",
"message": "No match reservation found for this client"
}
],
}

And now try the same PUT API with the client ID and it returns a 200 response code.

**Comment by suryayadavalli** [comment]
This is documentation issue. Documentation updated.

Documentation https://docs.hslynk.com/?urls.primaryName=Housing%20Match%20Service%20API#/default/PUT_matches-client-dedupClientId-status
