### ISSUE TITLE
Add name and address fields in the housingunit API.

### ISSUE THREAD

**Issue by logicsandeep** [hserv/coordinated-entry#389]
We don't need a new API for the address the housingunit API under the housing inventory (CES) should store the address  and lat/long fields like housing unit from bed list  APIs.

**Comment by suryayadavalli** [comment]
Resolved.
Commit id: https://github.com/hserv/coordinated-entry/commit/ef58ad2c579dce0ae6d091c8e0c38f6b9abc1dcd
