### ISSUE TITLE
Housing Inventory Service has been unstable

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#43]
@CTAJavier on 9/29/16 reported that is has crashed 5 times in the past 3 weeks.  Jenkins last reported a ces health crash last on Sept 16.  Maybe that's not working also?  or it's home app...  Either way we need to have it working for the demos soon.

**Comment by suryayadavalli** [comment]
Resolved and Verified after the fix.

Issue is with the recent changes to the DB to maintain Project ID as UUID as opposed to a string.  We will add auto regression tests to the deployment jobs to run right after any changes that are pushed into production , to ensure the stability of the system. 

CES_Health only monitors the health of the service but not functional aspects of the application. Will create separate issues for the to dos.
