### ISSUE TITLE
Branching for CES apps

### ISSUE THREAD

**Issue by suryayadavalli** [hserv/coordinated-entry#44]
To provide a more stable master branch, and more deliberate feature enhancement.

**Comment by eric-jahn** [comment]
Following this model: http://nvie.com/posts/a-successful-git-branching-model/ , which is where we're moving with hslynk as well.

**Comment by eric-jahn** [comment]
Okay, so we need to first create a release branch.  I think we should call the current release-1.0 and copy master over to it.  Then new stuff for this same release can go into release-1.0-maint and release-1.0-hotfix.  @suryayadavalli can you make those branches and close this issue?

**Comment by eric-jahn** [comment]
done
