### ISSUE TITLE
Test environment for CES services

### ISSUE THREAD

**Issue by suryayadavalli** [hserv/coordinated-entry#45]
This will allow us to immediately know when the CES service is down.  The health monitors currently only point out deployment issues.

**Comment by eric-jahn** [comment]
related to https://github.com/servinglynk/hmis-lynk-open-source-docs/issues/207

**Comment by eric-jahn** [comment]
@suryayadavalli Haven't we deployed a dev environment now for CES; is this an old duplicate issue?
