### ISSUE TITLE
Consistent audit fields in all the CES services

### ISSUE THREAD

**Issue by suryayadavalli** [hserv/coordinated-entry#47]
All the services have different ways to maintain audit fields (including names and types). Need to have an consistent naming and maintaining mechanism.  [uids, deletion, etc.]

**Comment by suryayadavalli** [comment]
Deployed and verified in production.  For all the CES APIs audit fields are captured and returned now in the response.

Here is an example of the response. Documentation is updated for all the APIs accordingly.

[
  {
     "householdMembershipId":"ef24fe58-05de-4e05-a994-6bbf513d6663",
     "globalClientId":"0080a1cf-cc2a-46c7-813c-b8bf5b111181",
     "dateCreated":"10-26-2016 06:52",
     "dateUpdated":"10-26-2016 06:52",
     "inactive":false,
     "relationshipToHeadOfHousehold":"Head of household's child",
     "globalHouseholdId":"92b48cfb-71f1-4ab8-b2c8-916e1e6613b4",
     "userId":"8b6c6ef2-87c7-47f0-8874-4cca6f09365c"
  },
  {
     "householdMembershipId":"7b207066-219a-4a25-a82a-8fa710860c6f",
     "globalClientId":"0080a1cf-cc2a-46c7-813c-b8bf5b111181",
     "dateCreated":"10-26-2016 06:52",
     "dateUpdated":"10-26-2016 06:52",
     "inactive":false,
     "relationshipToHeadOfHousehold":"Head of household's spoude or partner",
     "globalHouseholdId":"92b48cfb-71f1-4ab8-b2c8-916e1e6613b4",
     "userId":"8b6c6ef2-87c7-47f0-8874-4cca6f09365c"
  },
  {
     "householdMembershipId":"22382cd1-843f-443b-8484-c3e903bce85a",
     "globalClientId":"0080a1cf-cc2a-46c7-813c-b8bf5b111181",
     "dateCreated":"10-26-2016 06:52",
     "dateUpdated":"10-26-2016 06:52",
     "inactive":false,
     "relationshipToHeadOfHousehold":"Other: non-relation member",
     "globalHouseholdId":"92b48cfb-71f1-4ab8-b2c8-916e1e6613b4",
     "userId":"8b6c6ef2-87c7-47f0-8874-4cca6f09365c"
  }
]

**Comment by desaiuditd** [comment]
Which endpoints will be affected because of this ? @suryayadavalli
