### ISSUE TITLE
score calculation override

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#52]
We'll create a new survey boolean switch entitled "app-calculates-score-override".  For the current scenario with Monterey, it will be set to true.  If it's ever false, HMISLynk tabulates scores according to correct answers specified in the surveys.  Default will be false, so it's backwards compatible with Monterey's vi setup.

**Comment by eric-jahn** [comment]
@suryayadavalli: Is this an old duplicate issue of something we have since resolved?

**Comment by suryayadavalli** [comment]
@eric-jahn : need to go back and check the implementation detail. Will update the ticket shortly
