### ISSUE TITLE
Look up base schema for projects

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#74]
This allows a project's various occurrences within the various version-specific schema to be retrieved.

**Comment by suryayadavalli** [comment]
Fixed and deployed in production
https://github.com/hserv/coordinated-entry/commit/0c9d95075037633eaf637b81729dd5487838621a

**Comment by eric-jahn** [comment]
thanks, and is the raml updated, with a higher minor version number?
