### ISSUE TITLE
Client validation for survey API

### ISSUE THREAD

**Issue by suryayadavalli** [hserv/coordinated-entry#78]

**Comment by eric-jahn** [comment]
@suryayadavalli: could you add a description of this issue, since I'm not recalling the nature of this one.  Thanks!

**Comment by suryayadavalli** [comment]
While posting scores for the clients, we need to validate the client Id against the base schema to ensure that the we are posting the data to the existing / valid client and we the user who is posting the score is indeed eligible to post the scores for the client (based on project group). We have implement to include these checks in the POST / PUT  scores API

**Comment by suryayadavalli** [comment]
Resolved and deployed in Production.

https://github.com/hserv/coordinated-entry/commit/05de64e2bdc80f90789ae6c7dd1a98aa987eff13
