### ISSUE TITLE
[Housing Match] Unexpected behaviour for PUT /status

### ISSUE THREAD

**Issue by desaiuditd** [hserv/coordinated-entry#84]
```
PUT /house-matching-api/matches/client/ff6bdbc0-95af-40ab-8992-fb6aef35b688/status HTTP/1.1
Host: www.hmislynk.com
X-HMIS-TrustedApp-Id: 16631CFE-6909-4AC1-B4EB-57902AC7AF0A
Authorization: HMISUserAuth session_token= F549EED4AD734CE9BF474244AAF2D03B44FF9748080048E0B63A1045984490D3
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache
Postman-Token: 076a2882-695c-31e7-0128-170283e165ee

{
	status: '4',
	comments: '<p>Testing Again - Appointment is missed. Rain Check</p>',
	recepients: {
		toRecipients: [
			'udesai@scu.edu',
			'uditddesai@yahoo.co.in'
		]
	}
}
```

When I make this call from HOME App I get the blank / empty response.

```

```

And when I make this call from Postman, I get following response.

```
{
  "error": [
    {
      "code": "ERR_CODE_INVALID_REQUEST",
      "message": "Invalid request body"
    }
  ]
}
```

**Comment by suryayadavalli** [comment]
This is not a valid format for Postman. (The json strings should be in double quotes). From the iy might work because the way the frAmework handles the request data.

**Comment by desaiuditd** [comment]
I don't think so. Because HOME has been making rest of all other requests the same way. And they work properly. If the key includes any space character then only we need quotes. 

Also I see that the `recipient` is mentioned as an array in the documentation. That could be the reason.

**Comment by suryayadavalli** [comment]
@desaiuditd : can you check the spelling of the word "recepients" in your request and try again. There was another fix  I made to fix an issue with CC and BCC recipients but the Invalid Request Body response that you see should be due to the misspell of the word.

**Comment by eric-jahn** [comment]
@desaiuditd: Where are we at with this?  Is it resolved?

**Comment by suryayadavalli** [comment]
Closing the issue . Just adding the email I received during the testing , yesterday


---------- Forwarded message ----------
From: <support@hmislynk.com>
Date: Mon, Nov 7, 2016 at 8:57 AM
Subject: Client match process status update
To: udesai@scu.edu, uditddesai@yahoo.co.in, surya.yadavalli@gmail.com


Dear Agency Admin, 
The Coalition of Homeless Service Providers have identified a possible match for your sample 2 in MOSBE Pueblo del Mar Family Recovery Community. To access the client please enter this ID into the search field ff6bdbc0-95af-40ab-8992-fb6aef35b688 .

You have 3 days to make contact to with the client, please update the the client's progress through the process as quickly as possible. Time stamp will be collected when each option is pressed, please refer to the CARS policies and procedures manual if you have questions regarding timelines.

Thank you.
- CES System
