### ISSUE TITLE
survey scores not getting overridden with the latest score updates

### ISSUE THREAD

**Issue by suryayadavalli** [hserv/coordinated-entry#88]

**Comment by CTAJavier** [comment]
8f178714-ebf0-44c5-b2f8-e5f980d56b48
280e3723-4e4c-493c-b4c3-0844f17c4cd7

still getting abnormally high numbers please check on these

**Comment by suryabi** [comment]
Javier, looked into these clients again.  Apparently, as these scores are already processed for these clients, we need to do the following to fix the issue. For any new clients, we will not have this issue.

1. Delete eligible clients - as this entity has incorrectly calculated scores 
2. Delete scores for these clients  (or truncate entire data and submit the scores again) - As the scores are not overridden (earlier) but inserted as new scores we have multiple scores for the same client for each section. 
3. Update the scores again for the clients
4. Run score processing (POST /scores)

**Comment by eric-jahn** [comment]
@suryayadavalli : is this closed now?

**Comment by eric-jahn** [comment]
@suryayadavalli: can we close this?

**Comment by suryayadavalli** [comment]
Resolved, deployed in Production. @CTAJavier confirmed that the score calculation is working without any issues now.

commit # f717e99
