### ISSUE TITLE
Survey Views,

### ISSUE THREAD

**Issue by CTAJavier** [hserv/coordinated-entry#93]
we need flattened survey Views, example currently we have one table that says responses and has all of the responses for all of the questions ever submitted to HMISLynk. what we need is a view say for each of the VI SPDATS, so instead of Question name and Question description as fields from which we have to extract the or filer for specific values, we can simply have a dimension for question1, question2, question 3. which would be the answers collected in a submission ID linked to the client.

Thanks

**Comment by eric-jahn** [comment]
@CTAJavier : could you make an example mock-up spreadsheet of what you'd like to see exactly (just really brief sample of what it would contain), and Sandeep will estimate the level of effort based on this?

**Comment by CTAJavier** [comment]
![image](https://cloud.githubusercontent.com/assets/14897073/20811957/960553c0-b7c4-11e6-86aa-b18f168bad83.png)
as an example a very simple table with client ID | Survey Date | Survey Response ID | Submission ID| question 1 response | Q2 Response | Q3 responses|

**Comment by eric-jahn** [comment]
12/6/16: @logicsandeep spoke with @CTAJavier , and those requirements will be pasted here by @logicsandeep here.

**Comment by logicsandeep** [comment]
@CTAJavier   We found that the client_id was null for a lot of records in the response table.

**Comment by logicsandeep** [comment]
The issue #100 is created to investigate and resolve client_id null in the response table.

**Comment by eric-jahn** [comment]
On 12/13 @logicsandeep said he would try to wrap this up in 2-3 days.

**Comment by eric-jahn** [comment]
On 12/23/16 @logicsandeep reported that he should be checking this feature in on Monday 12/26.

**Comment by logicsandeep** [comment]
This task is completed.
https://github.com/servinglynk/hmis-lynk-open-source/commit/3a1269a66b59c508fe01ad775e26fd54fce4e10e
https://github.com/servinglynk/hmis-lynk-open-source/commit/acf03babfe1b31018ccf305e79754ef379d083a1
https://github.com/servinglynk/hmis-lynk-open-source/commit/4b4518e980d313ba4c31bb7027ee22ad6d48935b
https://github.com/servinglynk/hmis-lynk-open-source/commit/cfd6e362bf965ac747530eec3ac3cfb34098b75b

https://github.com/servinglynk/hmis-lynk-open-source/commit/ae0aadc3377d240ea61c3d82f59e2e19f4cd4b97
