### ISSUE TITLE
Global households disappeared 

### ISSUE THREAD

**Issue by CTAJavier** [hserv/coordinated-entry#94]
We previously had hundreds of global households in hmislynk for the Monterey project group.  Currently we only have 1. Please look into this and recover those households.

**Comment by suryayadavalli** [comment]
I verified the Apache logs and see that there is no calls that were made to delete the data, if its existing. Also, I have recreated the database from the back up we have 10 days back and it has also 97 records and with only one global household that belongs to Monterey. 

At this point, we do not have any other means to see how the data was deleted, if its existed in the first place. However, we will come up with a mechanism pretty soon to track any changes to the data (in terms of deletes) so we can trace back , if these kind of issues occur again. 

If you have spread sheet or any other file that has these global households, we will help uploading the data with a script . Please let us know .

**Comment by eric-jahn** [comment]
No further activity on this.  Closing.
