### ISSUE TITLE
Implement soft delete for all CES Apps

### ISSUE THREAD

**Issue by suryayadavalli** [hserv/coordinated-entry#95]
Please refer to #94 

Need to implement soft delete to track the changes (in terms of deletion) and to be able to restore in case of any accidental deletions to the data.  HOME app was concerned that they are not able to see the global households that they used to have earlier and we currently couldn't verify what caused this deletion.

**Comment by eric-jahn** [comment]
precursor is issue #78 , per @suryayadavalli on 12/20/2016.

**Comment by eric-jahn** [comment]
On 12/27/16: @suryayadavalli said this is somewhat coding involved.  Soft delete interceptor required.  Testing needed.  Tentative due date Friday 12/30.

**Comment by eric-jahn** [comment]
On 12/30/16 Surya said he deployed this for global households.  Still testing the other services, and he should be finished by 01/03/17.

**Comment by suryayadavalli** [comment]
Resolved, Deployed and verified in Production

https://github.com/hserv/coordinated-entry/commit/b066a55fe573ac40a573cdcb5ad68947087b01b8
