### ISSUE TITLE
Provide API to see match step where matches were successful or failing

### ISSUE THREAD

**Issue by eric-jahn** [hserv/coordinated-entry#98]
Conceived by @suryayadavalli, and discussed with @CTAJavier on 12/7/16.  

Allow privileged HOME App users (what levels/roles?) to view, either by project or by homeless client:

for a specific project:
-  the highest step at which matches were failing, and the itemized eligibility shortcoming(s) for the past X (paginated) unsuccessfully matched clients. 
- the successful eligibility criterion at each step for the past X (paginated) successfully matched clients. 

for a specific homeless client:
-  the highest step at which matches were failing, and the itemized eligibility shortcoming(s) for the past X (paginated) unsuccessfully matched projects. 
- the successful eligibility criterion at each step for the past X (paginated) successfully matched projects.

**Comment by eric-jahn** [comment]
12/13/16 @suryayadavalli reported he has finished the design, and expects to be finished by end of week.

**Comment by suryayadavalli** [comment]
Resolved, Deployed in production. 

There is a new API now to fetch the match process log, based on process id, Client Id, housing unit Id, and project Id.

Here is the link for API documentation 
https://anypoint.mulesoft.com/apiplatform/apis/#/portals/organizations/1d2d1eb1-46af-4ee8-aa04-bd79ed2764a3/apis/60339/versions/62798

Plese check the following API for details
/matchprocesslog

**Comment by eric-jahn** [comment]
Corresponding HOME App issue to implement this functionality: https://trello.com/c/sMXNup8S/164-implement-newly-available-match-process-succeed-fail-log-api-api-is-under-matchprocesslog-here-https-anypoint-mulesoft-com-apipl
